language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - nightly
    - hhvm

before_script:
    - composer install --dev
    
script:
    - if [[ $TRAVIS_PHP_VERSION == 5.4 ]];
        then phpunit --debug --coverage-text --coverage-clover build/logs/clover.xml;
        else phpunit --debug;
      fi

after_script:
    - if [ $TRAVIS_PHP_VERSION == 5.4 ]; then ./vendor/bin/test-reporter; fi

addons:
    code_climate:
        repo_token: ef2338aa4b8542e76c3d8f0a6d28a3890f296a12179290452bb60b8663edebf2
